name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Set up SSH
      run: |
        echo "Setting up SSH with the provided secrets."
        mkdir -p ~/.ssh 
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > my-ssh-key.pem
        chmod 600 my-ssh-key.pem
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        echo "SSH key and known_hosts set up."

    - name: Verify SSH setup
      run: |
        ls -la ~/.ssh
        echo "SSH setup completed without exposing secrets."
    
    - name: Deploy to EC2
      run: |
        ssh -i my-ssh-key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'SSH connection successful'"
        
        ssh -i my-ssh-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -x  # Enable debugging
          cd /node-deployment
          pm2 stop all || true
          git pull origin main
          npm install
          pm2 start all || true
        EOF
